"""Initial migration

Revision ID: 1e2c27ba7c73
Revises: 
Create Date: 2025-12-21 15:03:45.312438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2c27ba7c73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_id'), 'analysis_runs', ['id'], unique=False)
    op.create_table('competitor_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_stores_city'), 'competitor_stores', ['city'], unique=False)
    op.create_index(op.f('ix_competitor_stores_competitor_name'), 'competitor_stores', ['competitor_name'], unique=False)
    op.create_index(op.f('ix_competitor_stores_id'), 'competitor_stores', ['id'], unique=False)
    op.create_index(op.f('ix_competitor_stores_state'), 'competitor_stores', ['state'], unique=False)
    op.create_table('demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('median_income', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('median_age', sa.Float(), nullable=True),
    sa.Column('household_size', sa.Float(), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demographics_city'), 'demographics', ['city'], unique=False)
    op.create_index(op.f('ix_demographics_id'), 'demographics', ['id'], unique=False)
    op.create_index(op.f('ix_demographics_state'), 'demographics', ['state'], unique=False)
    op.create_table('publix_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('opening_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publix_stores_city'), 'publix_stores', ['city'], unique=False)
    op.create_index(op.f('ix_publix_stores_id'), 'publix_stores', ['id'], unique=False)
    op.create_index(op.f('ix_publix_stores_state'), 'publix_stores', ['state'], unique=False)
    op.create_index(op.f('ix_publix_stores_store_number'), 'publix_stores', ['store_number'], unique=True)
    op.create_table('zoning_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('acreage', sa.Float(), nullable=True),
    sa.Column('zoning_status', sa.String(), nullable=True),
    sa.Column('permit_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('record_date', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoning_records_city'), 'zoning_records', ['city'], unique=False)
    op.create_index(op.f('ix_zoning_records_id'), 'zoning_records', ['id'], unique=False)
    op.create_index(op.f('ix_zoning_records_parcel_id'), 'zoning_records', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_zoning_records_state'), 'zoning_records', ['state'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('predicted_store_size', sa.Integer(), nullable=True),
    sa.Column('key_factors', sa.JSON(), nullable=True),
    sa.Column('analysis_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_city'), 'predictions', ['city'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_state'), 'predictions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_state'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_city'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_zoning_records_state'), table_name='zoning_records')
    op.drop_index(op.f('ix_zoning_records_parcel_id'), table_name='zoning_records')
    op.drop_index(op.f('ix_zoning_records_id'), table_name='zoning_records')
    op.drop_index(op.f('ix_zoning_records_city'), table_name='zoning_records')
    op.drop_table('zoning_records')
    op.drop_index(op.f('ix_publix_stores_store_number'), table_name='publix_stores')
    op.drop_index(op.f('ix_publix_stores_state'), table_name='publix_stores')
    op.drop_index(op.f('ix_publix_stores_id'), table_name='publix_stores')
    op.drop_index(op.f('ix_publix_stores_city'), table_name='publix_stores')
    op.drop_table('publix_stores')
    op.drop_index(op.f('ix_demographics_state'), table_name='demographics')
    op.drop_index(op.f('ix_demographics_id'), table_name='demographics')
    op.drop_index(op.f('ix_demographics_city'), table_name='demographics')
    op.drop_table('demographics')
    op.drop_index(op.f('ix_competitor_stores_state'), table_name='competitor_stores')
    op.drop_index(op.f('ix_competitor_stores_id'), table_name='competitor_stores')
    op.drop_index(op.f('ix_competitor_stores_competitor_name'), table_name='competitor_stores')
    op.drop_index(op.f('ix_competitor_stores_city'), table_name='competitor_stores')
    op.drop_table('competitor_stores')
    op.drop_index(op.f('ix_analysis_runs_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###

