"""Add new data collection tables

Revision ID: 3bf360c86bbf
Revises: c3d28223380a
Create Date: 2025-12-21 20:11:32.941442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf360c86bbf'
down_revision = 'c3d28223380a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('traffic_data', sa.Column('city', sa.String(), nullable=True))
    op.add_column('traffic_data', sa.Column('state', sa.String(), nullable=True))
    op.create_index(op.f('ix_traffic_data_city'), 'traffic_data', ['city'], unique=False)
    op.create_index(op.f('ix_traffic_data_state'), 'traffic_data', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_data_state'), table_name='traffic_data')
    op.drop_index(op.f('ix_traffic_data_city'), table_name='traffic_data')
    op.drop_column('traffic_data', 'state')
    op.drop_column('traffic_data', 'city')
    # ### end Alembic commands ###

