"""Add parcel, zoning, and planning models

Revision ID: c3d28223380a
Revises: 1e2c27ba7c73
Create Date: 2025-12-21 16:35:35.176090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d28223380a'
down_revision = '1e2c27ba7c73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics', sa.Column('population_5yr_ago', sa.Integer(), nullable=True))
    op.add_column('demographics', sa.Column('metro_area', sa.String(), nullable=True))
    op.add_column('demographics', sa.Column('stores_per_capita', sa.Float(), nullable=True))
    op.add_column('zoning_records', sa.Column('planning_commission_record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'zoning_records', 'planning_commission_records', ['planning_commission_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zoning_records', type_='foreignkey')
    op.drop_column('zoning_records', 'planning_commission_record_id')
    op.drop_column('demographics', 'stores_per_capita')
    op.drop_column('demographics', 'metro_area')
    op.drop_column('demographics', 'population_5yr_ago')
    # ### end Alembic commands ###

